<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Privacy Policy | IW System</title>
    <meta name="description" content="privacy policy, statemnet, legal">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/sl-slide.css">
    <link rel ="shortcut icon" href="images/ico/icon.ico" />
    <script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <script src="js/vendor/jquery-1.9.1.min.js"></script>
    <script src="js/jquery.validate.min.js"></script>
</head>
<body>
    <!--Header-->
    <?php include('tmpl/header.php');  ?>

    <section class="title">
        <div class="container">
            <div class="row-fluid">
                <div class="span6">
                    <h1>Privacy Policy</h1>
                </div>
                <div class="span6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="index.php">Home</a> <span class="divider">/</span></li>
                        <li class="active">Privacy Policy</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- / .title -->       
    <section id="privacy" class="container">
        <div class="row-fluid">
            <div class="span7">
                <h4>Our commitment to privacy.</h4>
                    <p>Your privacy is important to us. To better protect your privacy, we have provided this notice explaining our online information practices and procedures.</p>
                    <p>Any personal information you provide to us including and similar to your name, phone and e-mail address helps us deliver a superior level of customer service. It enables us to give you convenient access to our products and services and focus on categories of greatest interest to you.</p>
                <h4>External Sites.</h4>
                    <p>IW System is not responsible for the content of external internet sites. You are advised to read the privacy policy of external sites before disclosing any personal information.</p>       
                <h4>Cookies and Related technologies.</h4>
                    <p>As is standard practice on many websites, our sites use “cookies” and other technologies to help us understand which parts of our websites are the most popular, where our visitors are going, and how much time they spend there. We use cookies and other technologies to study traffic patterns on our website, to make it even more rewarding as well as to study the effectiveness of our customer communications. And we use cookies to customize your experience and provide greater convenience each time you interact with us.</p>
                <h4>Google Analytics</h4>
                    <p>Our websites uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of our websites. By using our websites, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
                <h4>General Risks of using the Internet</h4>
                    <p>While we do our best to protect your personal information, we cannot guarantee the security of any information that you transmit to IW System and services we Operate. You are solely responsible for maintaining the secrecy of any passwords or other account information. In addition other Internet sites or services that may be accessible through our websites have separate data and privacy practices independent of us, hence we disclaim any responsibility or liability for their policies or actions.</p>
                    <p>Please contact those vendors and others directly if you have any questions about their privacy policies.</p>
                <h4>Changes to this privacy policy.</h4>
                    <p>Please note that this Privacy Policy may change from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent, and we expect most such changes will be minor. Regardless, we will post any Privacy Policy changes on this page and, if the changes are significant, we will provide a more prominent notice </p>
            </div>
            <div class="span2"></div>
            <div class="span3">
                <div class="pull-right">
                    <h6>Updated Versions</h6>
                    <div class="accordion" id="update-accordion">
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#update-accordion" href="#updated1">
                                    <i>Previous Version</i>
                                    <i class="icon icon-angle-down pull-right"></i>
                                </a>
                            </div>
                            <div id="updated1" class="accordion-body collapse">
                                <div class="accordion-inner">
                                    This is the latest and only version of the privacy policy. There hasn't been any updates yet.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </section>

    <!--Bottom-->
    <?php include('tmpl/bottom.php');  ?>

    <!--Footer-->
    <?php include('tmpl/footer.php');  ?>
    <!--/Footer-->

    <!--  Login form -->
    <?php include('tmpl/login-form.php');  ?>
    <!--  /Login form -->

<script src="js/vendor/bootstrap.min.js"></script>
<script src="js/main.js"></script>

</body>
</html>
